version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=MyS3cureP@ssw0rd2025!  # Change this to a secure password
      - ELASTICSEARCH_PASSWORD=MyS3cureP@ssw0rd2025!  # Ensure the same password for consistency
    networks:
      - elk
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_PASSWORD=MyS3cureP@ssw0rd2025!  # Ensure this matches the password for Elasticsearch
    networks:
      - elk
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: always

networks:
  elk:
    driver: bridge

volumes:
  esdata:
    driver: local

