name: Another Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # This is the environment for the workflow (Ubuntu)

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This step checks out your repository's code

    - name: Set up Python
      uses: actions/setup-python@v2  # This step sets up the Python environment
      with:
        python-version: '3.8'  # You can specify the Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt     # Install dependencies from requirements.txt

    - name: Run tests
      run: |
        pytest  # This runs your tests

